# Function that returns top100 hot songs of the moment & saving it in a .py file

In [1]:
%%writefile top100.py
def top100():
    # imports
    import pandas as pd
    import numpy as np
    import requests
    from bs4 import BeautifulSoup
    # BeautifulSoup setup
    url = 'https://www.billboard.com/charts/hot-100/'
    headers = {"Accept-Language": "en-US,en;q=0.5"}
    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, 'html.parser')
    # paths & empty lists
    title_path = 'h3.c-title.a-no-trucate'
    artist_path = 'span.c-label.a-no-trucate.a-font-primary-s'
    weeks_path = 'ul > li.lrv-u-width-100p > ul > li.lrv-u-width-100p.u-hidden\@tablet > ul > li:nth-child(5) > span'
    titles = []
    artists = []
    weeks = []
    # getting the data
    for i in range(len(soup.select("div.o-chart-results-list-row-container"))):
        titles.append(soup.select(title_path)[i].get_text(strip=True))
        artists.append(soup.select(artist_path)[i].get_text(strip=True))
        weeks.append(soup.select(weeks_path)[i].get_text(strip=True))
    # adding a rank
    rank = np.arange(len(soup.select("div.o-chart-results-list-row-container")))+1
    # creating a DataFrame
    return pd.DataFrame({
        'rank': rank,
    'song_title': titles,
    'artists': artists,
    'weeks_on_chart': weeks
    })

Overwriting top100.py

# Checking it works

In [3]:
from top100 import *
top100()

,rank,song_title,artists,weeks_on_chart
0,1,We Don't Talk About Bruno,"Carolina Gaitan, Mauro Castillo, Adassa, Rhenz...",8
1,2,Heat Waves,Glass Animals,57
2,3,Easy On Me,Adele,19
3,4,abcdefu,GAYLE,13
4,5,Stay,The Kid LAROI & Justin Bieber,32
...,...,...,...,...
95,96,All Too Well (Taylor's Version),Taylor Swift,14
96,97,Come Back As A Country Boy,Blake Shelton,5
97,98,Iffy,Chris Brown,5
98,99,Home Sweet,Russell Dickerson,5
99,100,Too Easy,Gunna & Future,16